# fly.toml app configuration file generated for heunets-assessment-kqxhdg on 2026-06-27T15:00:32Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'heunets-assessment-kqxhdg'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

  [build.args]
    VITE_API_URL = 'https://heunets-assessment-qs5hdq.fly.dev/api'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
